### ISSUE TITLE
Create a release?

### ISSUE THREAD

**Issue by matthiasdiener** [illinois-ceesd/logpyle#1]
Currently, logpyle has essentially the same code as the most recent versions of pytools.log and datapyle, just changing the references to these packages.

It also has docs and CI.
@inducer

**Comment by inducer** [comment]
Sure. Please add me as a co-owner on pypi (same username as here) when done.

**Comment by matthiasdiener** [comment]
Done: https://pypi.org/project/logpyle/

However,
![image](https://user-images.githubusercontent.com/1772435/94487203-34fb1080-01a6-11eb-96f8-42a098418e1c.png)

**Comment by inducer** [comment]
Nvm: https://pypi.org/user/inducer77/

**Comment by matthiasdiener** [comment]
Commands to create a release:

```bash
# Update logpyle/version.py
# Commit

$ python setup.py sdist bdist_wheel
$ twine upload dist/*
```
