### ISSUE TITLE
runalyzer-gather does not work with multiple input files

### ISSUE THREAD

**Issue by matthiasdiener** [illinois-ceesd/logpyle#21]
```console
$ runalyzer-gather -m summary.dat sod1d.dat*
Scanning...          [########################################] ETA ?
Traceback (most recent call last):
  File "/Users/mdiener/miniforge3/envs/ceesd/bin/runalyzer-gather", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/mdiener/Work/emirge/logpyle/bin/runalyzer-gather", line 416, in <module>
    main()
  File "/Users/mdiener/Work/emirge/logpyle/bin/runalyzer-gather", line 396, in main
    fmap = make_name_map(options.feature_map)
  File "/Users/mdiener/Work/emirge/logpyle/bin/runalyzer-gather", line 188, in make_name_map
    assert match is not None
AssertionError
```

Input files (rename to *.dat):

- [sod1d.dat-EYsYeJ.log](https://github.com/illinois-ceesd/logpyle/files/5336071/sod1d.dat-EYsYeJ.log)
- [sod1d.dat-XKivdD.log](https://github.com/illinois-ceesd/logpyle/files/5336072/sod1d.dat-XKivdD.log)

**Comment by inducer** [comment]
`-m` on `runalyzer-gather` triggers "file name-to-run-property" mapping, where components of the file name are mapped to run properties. It's just that what follows the `-m` on your command line is not a match expression. (See `--help`.) But I agree that the error message could be better.

**Comment by matthiasdiener** [comment]
> `-m` on `runalyzer-gather` triggers "file name-to-run-property" mapping, where components of the file name are mapped to run properties. It's just that what follows the `-m` on your command line is not a match expression. (See `--help`.) But I agree that the error message could be better.

OIC. I pushed a PR that should clarify this a bit.

**Comment by inducer** [comment]
Thanks! Did some complaining on the PR. *duck*
