### ISSUE TITLE
MacOS 3.9 test fails

### ISSUE THREAD

**Issue by inducer** [illinois-ceesd/logpyle#29]
In #27, @matthiasdiener says:

> I'll merge this even with the Python3.9-macos test failing. Let's hope they release a binary matplotlib package for this config.

I'm not a fan. I like green checkmarks. Could you add a shell snippet to skip that test for now?

**Comment by inducer** [comment]
(Otherwise I have to click around a lot to see if only the things that were supposed to fail actually failed.)

**Comment by matthiasdiener** [comment]
Ok, makes sense.
