### ISSUE TITLE
Remove from pytools and datapyle

### ISSUE THREAD

**Issue by inducer** [illinois-ceesd/logpyle#3]
Please create MRs to remove these bits from their source packages, pointing here instead.

**Comment by inducer** [comment]
- https://github.com/inducer/pytools/pull/41
- https://github.com/inducer/datapyle/commit/df92b0624409c9d73de6d7e894293ebe6c128421

**Comment by matthiasdiener** [comment]
Also, https://github.com/inducer/datapyle/pull/1 .
