### ISSUE TITLE
Create conda-forge package

### ISSUE THREAD

**Issue by matthiasdiener** [illinois-ceesd/logpyle#64]
https://conda-forge.org/docs/maintainer/adding_pkgs.html

**Comment by inducer** [comment]
Since there are no binary components, I don't really see the necessity (vs pip). Could you explain?

**Comment by matthiasdiener** [comment]
> Since there are no binary components, I don't really see the necessity (vs pip). Could you explain?

The thing that cam to my mind was that we are distributing scripts for users to run directly, ie, it's not just a library. But not very important.

**Comment by inducer** [comment]
`pip` does OK with distributing scripts in my experience.
