### ISSUE TITLE
Logging report bogus initial values

### ISSUE THREAD

**Issue by MTCam** [illinois-ceesd/logpyle#70]
When using logging as status reporter, it report bogus values at step 0.

```
step = 0, sim time: 0.000000e+00 s
------- P (min, max) (Pa) = (0.000000000e+00, 0.000000000e+00)
------- T (min, max) (K)  = (      0,       0)
------- step walltime: 24.2316 s, log walltime:      0 s
```

**Comment by inducer** [comment]
AFAIK @matthiasdiener and I had discussed this at some point, I agree that it needs to be fixed.

**Comment by matthiasdiener** [comment]
#72 solves this for the `log walltime` mentioned above. For the other quantities (`P` and `T` in the example above), is it just a matter of turning them into `PostLogQuantities`?

**Comment by MTCam** [comment]
> #72 solves this for the `log walltime` mentioned above. For the other relevant quantities (`P` and `T` in the example above), is it just a matter of turning them into `PostLogQuantities`?

We want to see the logged quantities before stepping occurs.  Does making them PostLogQuantities preclude that?

**Comment by matthiasdiener** [comment]
> > #72 solves this for the `log walltime` mentioned above. For the other relevant quantities (`P` and `T` in the example above), is it just a matter of turning them into `PostLogQuantities`?
> 
> We want to see the logged quantities before stepping occurs. Does making them PostLogQuantities preclude that?

Hmm, the difference is when the values for the quantities are gathered. For the `LogQuantity` classes (currently used mirgecom logging), they are gathered at the beginning of the timestep (at `tick_before`); The proposed change in illinois-ceesd/mirgecom#433 makes them getting gathered at the end of the time step (at `tick_after`). I'm not sure which way makes more sense, but illinois-ceesd/mirgecom#433 at least appears to fix the reporting of bogus values.

**Comment by MTCam** [comment]
> > > #72 solves this for the `log walltime` mentioned above. For the other relevant quantities (`P` and `T` in the example above), is it just a matter of turning them into `PostLogQuantities`?
> > 
> > 
> > We want to see the logged quantities before stepping occurs. Does making them PostLogQuantities preclude that?
> 
> Hmm, the difference is when the values for the quantities are gathered. For the `LogQuantity` classes (currently used in mirgecom logging), they are gathered at the beginning of the timestep (at `tick_before`); The proposed change in [illinois-ceesd/mirgecom#433](https://github.com/illinois-ceesd/mirgecom/pull/433) makes them getting gathered at the end of the time step (at `tick_after`). I'm not sure which way makes more sense, but [illinois-ceesd/mirgecom#433](https://github.com/illinois-ceesd/mirgecom/pull/433) at least appears to fix the reporting of bogus values.

Ah, then maybe we should just be calling tick_before and tick_after before the first step?!

**Comment by matthiasdiener** [comment]
> Ah, then maybe we should just be calling tick_before and tick_after before the first step?!

I think that would throw off the machinery a bit. When seeing the values, would it be better to see them how they are before the step executes or after?

**Comment by MTCam** [comment]
> > Ah, then maybe we should just be calling tick_before and tick_after before the first step?!
> 
> I think that would throw off the machinery a bit. When seeing the values, would it be better to see them how they are before the step executes or after?

We want to see both.  We must see them before stepping starts, and then after stepping ends.  In between those two points, the user needs to be able to indicate how often they are written to screen.  Whether the intermediate times are before or after the step is less critical.

**Comment by matthiasdiener** [comment]
> > > Ah, then maybe we should just be calling tick_before and tick_after before the first step?!
> > 
> > 
> > I think that would throw off the machinery a bit. When seeing the values, would it be better to see them how they are before the step executes or after?
> 
> We want to see both. We must see them before stepping starts, and then after stepping ends. In between those two points, the user needs to be able to indicate how often they are written to screen. Whether the intermediate times are before or after the step is less critical.

Yeah, my question was I was regarding the status for a single step, ie, are the values gathered before or after the step. If I understand you right, it doesn't really matter, so  illinois-ceesd/mirgecom#433 might be the way to go

**Comment by MTCam** [comment]
> > > > Ah, then maybe we should just be calling tick_before and tick_after before the first step?!
> > > 
> > > 
> > > I think that would throw off the machinery a bit. When seeing the values, would it be better to see them how they are before the step executes or after?
> > 
> > 
> > We want to see both. We must see them before stepping starts, and then after stepping ends. In between those two points, the user needs to be able to indicate how often they are written to screen. Whether the intermediate times are before or after the step is less critical.
> 
> Yeah, my question was I was regarding the status for a single step, ie, are the values gathered before or after the step. If I understand you right, it doesn't really matter, so [illinois-ceesd/mirgecom#433](https://github.com/illinois-ceesd/mirgecom/pull/433) might be the way to go.

Oh got it, sorry yeah.  In the middle of the simulation, it matters not whether the values are reported before or after.
