### ISSUE TITLE
Drop single-run mode of runalyzer-gather?

### ISSUE THREAD

**Issue by matthiasdiener** [illinois-ceesd/logpyle#95]
single-run mode leads to a lot of code duplication in runalyzer-gather.

As far as I can see, the only advantage of single-run mode is that the resulting file is slightly smaller due to the missing run_id column in each table.

Also, some functionality of runalyzer does not work with the single-run mode (e.g., the `runprops` command).

**Comment by inducer** [comment]
I'm OK with dropping it.
